// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealState.Data;

#nullable disable

namespace RealState.Migrations
{
    [DbContext(typeof(RealStateContext))]
    [Migration("20230327071127_AddCneRefToInscriptions")]
    partial class AddCneRefToInscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("RealState.Models.Cne", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Cne");
                });

            modelBuilder.Entity("RealState.Models.Inscription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cneid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("attention_number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<int>("fojas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("number")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Cneid");

                    b.ToTable("Inscription");
                });

            modelBuilder.Entity("RealState.Models.Inscription", b =>
                {
                    b.HasOne("RealState.Models.Cne", "Cne")
                        .WithMany()
                        .HasForeignKey("Cneid");

                    b.Navigation("Cne");
                });
#pragma warning restore 612, 618
        }
    }
}
